### ISSUE TITLE
Possible to get total seconds uptime?

### ISSUE THREAD

**Issue by wrybread** [YiannisBourkelis/Uptime-Library#1]
Very nice and thank you for this library! I have a project where I need to get total seconds of uptime for formatting elsewhere. Is it possible to get the total uptime in seconds with this library?

**Comment by YiannisBourkelis** [comment]
@wrybread you can use the millis() function and convert it to seconds. https://www.arduino.cc/reference/en/language/functions/time/millis/

**Comment by bobemoe** [comment]
Er, isn't part of the point of using this library is to avoid the 49day wrap with `millis`?

I think this should be reopened. It would be great to be able to get the total in seconds.

Thanks

**Comment by YiannisBourkelis** [comment]
@bobemoe correct. There is no function in the library to convert days,hours,minutes,seconds,Millisecons to seconds, but you can compute it yourself by converting and adding the appropriate values to seconds. 
E.g.  uptime::getHours() * 60 * 60
