### ISSUE TITLE
name followed by '::' must be a class or namespace name

### ISSUE THREAD

**Issue by Boby71** [YiannisBourkelis/Uptime-Library#2]
Hi,
I added the uptime-library to my ESP32 project. When using any of the functions of the example, e.g....
`uptime::calculateUptime();`
I always get the following compile error: **name followed by '::' must be a class or namespace name**
Any idea what could be wrong? Thanks!

**Comment by Boby71** [comment]
Info: Added...
`#include "uptime.h"`
to my sketch and now it's compiling.
Maybe you want to add this to your example

**Comment by Boby71** [comment]
Just noticed that there are two different examples and everything is right anyway in your example. Sorry mate, my fault.

**Comment by YiannisBourkelis** [comment]
@Boby71 your are welcome. Nice to hear you solved it.
