### ISSUE TITLE
"error: 'String' does not name a type" compile error

### ISSUE THREAD

**Issue by abregnsbo** [YiannisBourkelis/Uptime-Library#4]
Using Arduino Cloud Web Editor, when I add:
  `#include "uptime.h"`
or
  `#include "uptime_formatter.h"`

I get the compile error:
`In file included from /home/builder/opt/libraries/latest/uptime_library_1_0_0/src/uptime_formatter.cpp:21:0:
/home/builder/opt/libraries/latest/uptime_library_1_0_0/src/uptime_formatter.h:32:12: error: 'String' does not name a type
static String getUptime();
^~~~~~`

I have tried to add the following line:
  `#include "Arduino.h"`
but this did not help.

**Comment by YiannisBourkelis** [comment]
@abregnsbo I would like to help you resolve this issue, but I do not have access to the Arduino Cloud Web Editor so I can not reproduce it.

**Comment by YiannisBourkelis** [comment]
@abregnsbo if you solved the issue I will close it
